# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170421_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Subunion',
            fields=[
                ('suid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='subunion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.Subunion'),
        ),
    ]
