# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170421_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='aaid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='aaid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='aid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
