# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_activity_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='aaid',
            field=models.IntegerField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
