# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170426_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='begin_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='signin_begin_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='signin_end_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='send_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='receive_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkin_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='signin_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_at',
            field=models.IntegerField(null=True),
        ),
    ]
