# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170427_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='aaid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
