# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20170428_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_path',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/None/no-img.jpg', upload_to='photos/'),
        ),
    ]
