# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20170428_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
