# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20170428_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='poster',
            field=models.ImageField(default='poster/None/no-img.jpg', upload_to='poster/'),
        ),
    ]
