# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20170503_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='bbid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='bid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='send_at',
            field=models.IntegerField(null=True),
        ),
    ]
