# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20170504_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, null=True)),
                ('is_career', models.BooleanField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='subunion',
        ),
        migrations.AddField(
            model_name='department',
            name='subunion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='base.Subunion'),
        ),
        migrations.AddField(
            model_name='user',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='base.Formation'),
        ),
    ]
