# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20170507_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wid_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
