# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_user_wid_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ddid',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
