# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_department_ddid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dismissed',
            field=models.BooleanField(default=0),
        ),
    ]
